### PR TITLE
Edit files with monaco editor.

### PR DESCRIPTION
**Pull request by Wojbie**
This adds ability for logged in user to edit contents of files stored in shitty using [monaco editor](https://microsoft.github.io/monaco-editor/) and using its nice code highlighers, key shortcuts and other fancy stuff.
Sadly due to limitations of monaco editor this is only possible from desktop not from mobile devices.

Sidenote - in future when/if monaco supports the mobile devices this could be also used as current /paste replacement. For now opening editor when not logged it shows editor in read-only mode to showcase that.

### CODE REVIEW

**Comment by Lemmmy** [comment]
!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1!!!!!1

**Comment by Wojbie** [comment]
Eloquent as ever i see.

**Comment by Lemmmy** [comment]
It's working great, really splendid work! I've made a few minor formatting changes to the code, as well as some changes to the spacing in the popup:



If you're happy with the changes, then I'm happy to merge.

**Comment by Wojbie** [comment]
Awesome you got that buttons to line up. And yea it all looks good for me.

**Pull request merged**
